### ISSUE TITLE
CLASSIFY error

### ISSUE THREAD

**Issue by Song-10-YF** [simonorozcoarias/Inpactor2#2]
Hi @simonorozcoarias,
I'm running "python3 Inpactor2_utils.py -u CLASSIFY -o . /output -t 20 -f Inpactor2_library.fasta" with the following error: "FileNotFoundError: [Errno 2] No such file or directory: '/home/bioml/ Projects/PhD/OE2/Repo/Inpactor2/test1/InpactorDB_non_redundant_final_V4.fasta.filtered.kmers'", I'm not sure what this file is? Where do I install it?
Looking forward to your reply, thanks!

**Comment by simonorozcoarias** [comment]
Hi @Song-10-YF 
It was a bug in the script. Now it seems to run properly. Please check it and let me know if everything is ok now. Thank you for using Inpactor2!

Best regards,

Simon.

**Comment by Song-10-YF** [comment]
Hi @simonorozcoarias,
I rerun the code with the updated "Inpactor2_utils.py", but the following errors are still reported:
WARNING: Missing -l or --lineage-names parameter, using by default: yes
Traceback (most recent call last):
  File "Inpactor2_utils.py", line 563, in <module>
    retraining_class(outputDir+'/'+file_name+'.kmers', outputDir)
NameError: name 'file_name' is not defined

There is another problem. I used "-C 5" and the program stopped at this step:
"INFO: Doing cycle # 4
INFO: Splitting input sequences into chunks of size 50000 and converting them into one-hot coding ...
INFO: Splitting of input sequences done!!!! [time=17.589149713516235]
INFO: Predicting which genomic sections contains LTR-RTs...
INFO: LTR-RTs containing prediction done!!!! [time=13.700386047363281]
INFO: Extracting sequences predicted as LTR-RTs ..."
It is normal when I only run 3 rounds.

Looking forward to your reply, thanks!

**Comment by simonorozcoarias** [comment]
Hi @Song-10-YF 
It seemed to be an error in a variable name, but it should be fixed know. Please check and let me know. 

About the problem with the cycles, I would need see the complete output. Please send it to me by email. How long are your sequences?

Best regards,

**Comment by Song-10-YF** [comment]
Hi @simonorozcoarias,
I rerun the code "python3 Inpactor2_utils.py -u CLASSIFY -o /home/yurm/software/Inpactor2/Tetra -t 128 -f /home/yurm/software/Inpactor2/Tetra/Inpactor2_library.fasta"
with the updated "Inpactor2_utils.py", but the following errors are still reported:

WARNING: Missing -l or --lineage-names parameter, using by default: yes
Traceback (most recent call last):
  File "Inpactor2_utils.py", line 563, in <module>
    retraining_class(outputDir+'/'+fastafile+'.kmers', outputDir)
  File "Inpactor2_utils.py", line 387, in retraining_class
    training_data = pd.read_csv(kmer_file)
  File "/home/yurm/anaconda3/envs/Inpactor2/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/yurm/anaconda3/envs/Inpactor2/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/yurm/anaconda3/envs/Inpactor2/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/yurm/anaconda3/envs/Inpactor2/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/yurm/anaconda3/envs/Inpactor2/lib/python3.7/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/yurm/anaconda3/envs/Inpactor2/lib/python3.7/site-packages/pandas/io/parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "/home/yurm/anaconda3/envs/Inpactor2/lib/python3.7/site-packages/pandas/io/common.py", line 652, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/yurm/software/Inpactor2/Tetra//home/yurm/software/Inpactor2/Tetra/Inpactor2_library.fasta.kmers'

The second question, my genome is almost 267 Mb. The directories are all files with the prefix "predicted_ids_", which are stuck running.

Looking forward to your reply, thanks!

**Comment by simonorozcoarias** [comment]
Hi @Song-10-YF, Can you try again? It was a small issue when getting the file name from the parameters.

Best regards,

**Comment by Song-10-YF** [comment]
I rerun the code "python3 Inpactor2_utils.py -u CLASSIFY -o /home/yurm/software/Inpactor2/Testing/toy_execution -t 128 -f /home/yurm/software/Inpactor2/Testing/toy_execution/Inpactor2_library.fasta" (test data) with the updated "Inpactor2_utils.py", but the following error occurs:

ValueError: Shape of passed values is (2, 2), indices imply (1, 1).
Looking forward to your replay, thanks.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simonorozcoarias/Inpactor2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simonorozcoarias/Inpactor2] CLASSIFY error (Issue #2)





 
Hi @Song-10-YF, Can you try again? It was a small issue when getting the file name from the parameters.
 
Best regards,

**Comment by simonorozcoarias** [comment]
Hi @Song-10-YF. Sorry for the late answer. I just fixed the issue and I have tried it with the sample dataset provided by the repo. Until now, I haven't got more errors, so hopely you finally should be able to execute the Inpactor2_util.py script.

Let me know if everything seems nice.

Best,

Simon.

**Comment by Song-10-YF** [comment]
Hi @simonorozcoarias,
Now it works fine, thank you very much.

Best,
Song
